unique_name: Product Dim
object_type: dimension
label: Product Dim
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    folder: Product Attributes
    levels:
      - unique_name: Product Name
level_attributes:
  - unique_name: Product Name
    label: Product Name
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: true
    key_columns:
      - productkey_change
    name_column: englishproductname
type: standard
