unique_name: Product Dim
object_type: dimension
label: Product Dim
hierarchies:
  - unique_name: Product Hierarchy
    label: Product Hierarchy
    folder: Product Attributes
    levels:
      - unique_name: Product Line
      - unique_name: Product Category
      - unique_name: Product Name
level_attributes:
  - unique_name: Product Name
    label: Product Name
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: true
    key_columns:
      - productkey_change
    name_column: englishproductname
    sort_column: empty_value
  - unique_name: Product Category
    label: Product Category
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: false
    key_columns:
      - productsubcategorykey
    name_column: productsubcategoryname
    sort_column: empty_value
  - unique_name: Product Line
    label: Product Line
    contains_unique_names: false
    dataset: dimproduct
    is_unique_key: true
    key_columns:
      - productline
    name_column: productline
type: standard
